task: "docvqa_test"
test_split: test
process_results: !function utils.docvqa_test_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.docvqa_test_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
include: _default_template_docvqa_yaml
