task: "infovqa_val"
test_split: validation
output_type: generate_until
process_results: !function utils.infovqa_process_results
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nGive the reason and then write your final answer in the format 'Answer: X' where X is the answer to the question."
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
include: _default_template_infovqa_yaml